import type { Course } from '../types/Course';

export const COURSES: Course[] = [
  {
    id: crypto.randomUUID(),
    title: 'HTML5, CSS y JS para principiantes',
    url: './curso1.jpg',
    price: 200,
    priceWithDiscount: 15,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Curso de comida para principiantes',
    url: './curso2.jpg',
    price: 150,
    priceWithDiscount: 15,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Guitarra para principiantes',
    url: './curso3.jpg',
    price: 250,
    priceWithDiscount: 30,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Huerto en tu casa',
    url: './curso4.jpg',
    price: 300,
    priceWithDiscount: 40,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Decoración con productos de tu hogar',
    url: './curso5.jpg',
    price: 200,
    priceWithDiscount: 20,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Diseño web para principiantes',
    url: './curso1.jpg',
    price: 150,
    priceWithDiscount: 15,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Comida Mexicana para principiantes',
    url: './curso2.jpg',
    price: 250,
    priceWithDiscount: 15,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Estudio Musical en tu casa',
    url: './curso3.jpg',
    price: 200,
    priceWithDiscount: 15,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Cosecha tus propias frutas y verduras',
    url: './curso4.jpg',
    price: 300,
    priceWithDiscount: 30,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'Prepara galletas caseras',
    url: './curso5.jpg',
    price: 250,
    priceWithDiscount: 25,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: 'JavaScript Moderno con ES6',
    url: './curso1.jpg',
    price: 280,
    priceWithDiscount: 35,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
  {
    id: crypto.randomUUID(),
    title: '100 Recetas de Comida Natural',
    url: './curso2.jpg',
    price: 300,
    priceWithDiscount: 40,
    user: {
      id: crypto.randomUUID(),
      name: 'Juan Pedro',
      email: 'juanpedro@gmail.com',
      rating: './estrellas.png',
    },
  },
];
